#!/usr/bin/env bash
set -e

git push origin src
git checkout -B master
npm run build
git add --force public/pages/* public/style.css
git commit -m 'updated build'
git push origin --force master
git checkout src
